version: "3"

services:
  react:
    container_name: react
    build:
      context: .
      dockerfile: ./Dockerfiles/build_react/Dockerfile
    volumes: 
      - ./react:/var/react_app
    ports:
      - 3000:3000